[linux]
node01 ansible_host=192.168.10.11
node02 ansible_host=192.168.10.12
docker01 ansible_host=192.168.10.20

[linux:vars]
ansible_user=ansible
ansible_python_interpreter=/usr/bin/python3

[monitoring]
docker01
